version: '3'
services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    volumes:
      - ./bdatos:/var/lib/mysql
    expose:
      - 3306
    networks:
      - mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mysql
  web:
    image: jazzdd/alpine-flask
    expose:
      - 80
    volumes:
      - .:/app
    networks:
      - flask
      - mysql
  reverse_proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flask
networks:
  mysql:
    driver: bridge
  flask:
    driver: bridge
