version: '3'
services:
  web:
    image: jazzdd/alpine-flask
    expose:
      - 80
    volumes:
      - ~/Documents/dev/python_nginx:/app
    networks:
      - flask
  reverse_proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ~/Documents/dev/python_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flask
networks:
  flask:
    driver: bridge
